POST http://localhost:3007/api/Users/update HTTP/1.1
content-type: application/json

{
 "id": "2",
 "Contacts": "076 454 6645",
 "Surname": "Ledwaba",
 "Names": "David"
}
###


POST http://localhost:3007/api/Gender/update 
content-type: application/json

{
 "Gender": "Sex",
 "Sex": "Male"
}
###


POST http://localhost:3007/api/Skintexture/update
content-type: application/json

{
 "Skintexture": "typesOfSkin",
 "typesOfSkin": "Oily Skin"
}
###



GET http://localhost:3007/api/Users

###


GET http://localhost:3007/api/Skintexture

###